version: '3.1'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    # Maps the ports to the machine.
    # In this case, 15432 to not collide
    # with perhaps other postgres instances.
    ports:
      - 5432:15432
    # Exposes the port to the current virtual
    # compose network.
    expose:
      - 5432
  redis:
    image: bitnami/redis:6.0
    env_file:
      - .env
    # Maps the ports to the machine.
    ports:
      - 6379:6379
    # Exposes the port to the current virtual
    # compose network.
    expose:
      - 6379
