version: '3.1'
services:
  db:
    image: postgres:13
    env_file:
      - .env
    # Maps the ports to the machine.
    # In this case, 15432 to not collide
    # with perhaps other postgres instances.
    ports:
      - 5432:15432
    # Exposes the port to the current virtual
    # compose network.
    expose:
      - 5432
  redis:
    image: bitnami/redis:6.0
    env_file:
      - .env
    # Maps the ports to the machine.
    ports:
      - 6379:6379
    # Exposes the port to the current virtual
    # compose network.
    expose:
      - 6379
  server:
    working_dir: /code
    build:
      context: ./application
    # Maps the port to the machine, so the
    # web interface can be queried and also
    # the websockets work appropriately to
    # the front end.
    ports:
      - 8000:8000
    # This port is exposed to enable the bot
    # connecting to it.
    expose:
      - 8000
    # This is for a development deploy. This
    # volume will be synchronized to the /code
    # directory inside the image. Everything
    # will be available there.
    volumes:
      - ./application:/code