# Generated by Django 3.0 on 2020-09-28 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_]*?(-[a-zA-Z0-9_]+)*$')]),
        ),
    ]
